"""empty message

Revision ID: edb66efdf733
Revises: 
Create Date: 2023-05-10 01:27:01.876801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb66efdf733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('game',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('game_url', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=500), nullable=True),
    sa.Column('platform', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('developer', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=500), nullable=True),
    sa.Column('freetogame_profile_url', sa.String(length=500), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
